// Copyright (c) Huawei Technologies Co., Ltd. 2022-2022. All rights reserved.

// 环境变量常量配置
package env

const (
	ConfigFile                          = "CONFIG_FILE"
	Region                              = "REGION"
	SupportRegions                      = "SUPPORT_REGIONS"
	FleetQuota                          = "FLEET_QUOTA"
	WebHttpPort                         = "WEB_HTTP_PORT"
	WebHttpsPort                        = "WEB_HTTPS_PORT"
	EnableHttps                         = "ENABLE_HTTPS"
	EnableHttp                          = "ENABLE_HTTP"
	WebHttpsAddr                        = "WEB_HTTPS_ADDR"
	HttpsCertFile                       = "HTTPS_CERT_FILE"
	HttpsKeyFile                        = "HTTPS_KEY_FILE"
	RSAPublicFile                       = "RSA_PUBLIC_FILE"
	RSAPrivateFile                      = "RSA_PRIVATE_FILE"
	GCMKey                              = "GCM_KEY"
	GCMNonce                            = "GCM_NONCE"
	MysqlAddress                        = "MYSQL_ADDRESS"
	MysqlUser                           = "MYSQL_USER"
	MysqlPassword                       = "MYSQL_PASSWORD"
	MysqlDBName                         = "MYSQL_DB_NAME"
	MysqlCharset                        = "MYSQL_CHARSET"
	ServiceAK                           = "SERVICE_AK"
	ServiceSK                           = "SERVICE_SK"
	ServiceDomainId                     = "SERVICE_DOMAIN_ID"
	EnableTokenCheck                    = "ENABLE_TOKEN_CHECK"
	DefaultFleetRegion                  = "DEFAULT_FLEET_REGION"
	DefaultFleetSpecification           = "DEFAULT_FLEET_SPECIFICATION"
	DefaultFleetProtectPolicy           = "DEFAULT_FLEET_PROTECT_POLICY"
	DefaultFleetProtectTimeLimit        = "DEFAULT_FLEET_PROTECT_TIME_LIMIT"
	DefaultFleetSessionTimeoutSeconds   = "DEFAULT_FLEET_SESSION_TIMEOUT_SECONDS"
	DefaultFleetMaxSessionNumPerProcess = "DEFAULT_FLEET_MAX_SESSION_NUM_PER_PROCESS"
	DefaultFleetPolicyPeriod            = "DEFAULT_FLEET_POLICY_PERIOD"
	DefaultFleetNewSessionNumPerCreator = "DEFAULT_FLEET_NEW_SESSION_NUM_PER_CREATOR"
	MaxProcessNumPerFleet               = "MAX_PROCESS_NUM_PER_FLEET"
	DefaultFleetBandwidth               = "DEFAULT_FLEET_BANDWIDTH"
	LogRotateSize                       = "LOG_ROTATE_SIZE"
	LogBackupCount                      = "LOG_BACKUP_COUNT"
	LogMaxAge                           = "LOG_MAX_AGE"
	DefaultScalingInterval              = "DEFAULT_SCALING_INTERVAL"
	DefaultGroupMaxSize                 = "DEFAULT_GROUP_MAX_SIZE"
	DefaultGroupMinSize                 = "DEFAULT_GROUP_MIN_SIZE"
	DefaultGroupDesiredSize             = "DEFAULT_GROUP_DESIRED_SIZE"
	AASSEnableHmac                      = "AASS_ENABLE_HMAC"
	AASSHmacAK                          = "AASS_HMAC_AK"
	AASSHmacSK                          = "AASS_HMAC_SK"
	AppGatewayEnableHmac                = "APPGATEWAY_ENABLE_HMAC"
	AppGatewayHmacAK                    = "APPGATEWAY_HMAC_AK"
	AppGatewayHmacSK                    = "APPGATEWAY_HMAC_SK"
	FleetDiskSize                       = "FLEET_DISK_SIZE"
	FleetVolumeType                     = "FLEET_VOLUME_TYPE"
	FleetDiskType                       = "FLEET_DISK_TYPE"
	FleetEipShareType                   = "FLEET_EIP_SHARE_TYPE"
	EnterpriseProject                   = "ENTERPRISE_PROJECT"
	JwtKey                              = "JWTKEY"
	JwtTokenLifetime                    = "JWT_TOKEN_LIFETIME"
	SessionLifeTime                     = "LOGIN_SESSION_LIFETIME"
	RedisAddress                        = "REDIS_ADDRESS"
	RedisPassword                       = "REDIS_PASSWORD"
	RedisMaxConn                        = "REDIS_MAX_CONN"
	DefaultImageRef                     = "DEFAULT_IMAGE_REF"
	DefaultImageFlavor                  = "DEFAULT_IMAGE_FLAVOR"
	DefaultScriptPath                   = "DEFAULT_SCRIPT_PATH"
	DefaultAuxProxyPath                 = "DEFAULT_AUXPROXY_PATH"
	ProfileStorageRegion                = "PROFILE_STORAGE_REGION"
	DefaultLoginPassword                = "DEFAULT_LOGIN_PASSWORD"
)
