// Copyright (c) Huawei Technologies Co., Ltd. 2022-2022. All rights reserved.

// paramter_key
package directer

const (
	WfKeyRegion              = "region"
	WfKeyFleet               = "fleet"
	WfKeyFleetId             = "fleet.id"
	WfKeyProjectId           = "fleet.project_id"
	WfKeyMinimum             = "fleet.minimum"
	WfKeyMaximum             = "fleet.maximum"
	WfKeyDesired             = "fleet.desired"
	WfKeyScalingInterval     = "fleet.scaling_interval_minutes"
	WfKeyBandwidth           = "fleet.bandwidth"
	WfKeyEnableAutoScaling   = "fleet.enable_auto_scaling"
	WfKeyProtectionPolicy    = "fleet.server_session_protection_policy"
	WfKeyProtectionTimeLimit = "fleet.server_session_protection_time_limit_minutes"
	WfKeyBuildId             = "fleet.build_id"
	WfKeySpecification       = "fleet.instance_specification"
	WfKeyInstanceTags        = "fleet.instance_tags"
	WfKeyEnterpriseProjectId = "fleet.enterprise_project_id"

	WfKeyScalingGroup       = "scaling_group"
	WfKeyScalingGroupId     = "scaling_group.id"
	WfKeyVpcId              = "scaling_group.vpc_id"
	WfKeySubnetId           = "scaling_group.subnet_id"
	WfKeySecurityGroupId    = "scaling_group.security_group_id"
	WfKeyResourceDomainId   = "scaling_group.resource_domain_id"
	WfKeyResourceAgencyName = "scaling_group.resource_agency_name"
	WfKeyResourceProjectId  = "scaling_group.resource_project_id"

	WfKeyProcessConfiguration = "runtime_configuration.process_configurations"
	WfKeyActivationTimeout    = "runtime_configuration.server_session_activation_timeout_seconds"
	WfKeyConcurrentPerProcess = "runtime_configuration.max_concurrent_server_sessions_per_process"
	WfKeyInboundPermissions   = "inbound_permissions"

	WfKeyBuild             = "build"
	WfKeyBuildUuid         = "build.id"
	WfKeyImageId           = "build.image_id"
	WfKeyBuildRegion       = "build.image_region"
	WfKeyBuildImageId      = "build_image_id"
	WfKeyBuildBucket       = "build.storage_bucket_name"
	WfKeyBuildKey          = "build.storage_key"
	WfKeyBuildECSId        = "build_ecs_id"
	WfKeyBuildName         = "build.name"
	WfKeyBuildVersion      = "build.version"
	WfKeyImageRef          = "image_ref"
	WfKeyBuildVpcId        = "build_vpc_id"
	WfKeyBuildSubnetId     = "build_subnet_id"
	WfKeyBandwidthName     = "bandwidth_name"
	WfKeyBandwidthType     = "bandwidth_type"
	WfKeyBuildBandwidth    = "build_bandwidth"
	WfKeyBandwidthId       = "bandwidth_id"
	WfKeySecurityGroupName = "security_group_name"
	WfKeySubnetName        = "subnet_name"
	WfKeySubnetCidr        = "subnet_cidr"
	WfKeySubnetGatewayIp   = "subnet_gateway_ip"
	WfKeyVpcName           = "vpc_name"
	WfKeyVpcCidr           = "vpc_cidr"

	WfKeyOriginProjectId     = "origin_project_id"
	WfKeyOriginDomainId      = "origin_domain_id"
	WfKeyResourceKeypairName = "keypair_name"
	WfKeyIamAgencyName       = "iam_agency_name"
	WfKeyScalingGroupName    = "scaling_group_name"
	WfKeyEipType             = "eip_type"
	WfDnsConfig              = "dns_config"
	WfKeyRetryTimes          = "retry_times"
	WfKeyRequestId           = "request_id"
)
